from __future__ import annotations

import re
from pathlib import Path

from locklab.circuit import Circuit, CircuitError, Gate, VERILOG_IDENTIFIER


INPUT_PATTERN = re.compile(r"^INPUT\s*\(\s*([^()]+?)\s*\)$", re.IGNORECASE)
OUTPUT_PATTERN = re.compile(r"^OUTPUT\s*\(\s*([^()]+?)\s*\)$", re.IGNORECASE)
GATE_PATTERN = re.compile(
    r"^([^=\s]+)\s*=\s*([A-Za-z]+)\s*\((.*?)\)\s*$",
    re.IGNORECASE,
)
GATE_ALIASES = {"BUFF": "BUF"}


class BenchError(CircuitError):
    """Raised when a BENCH file contains unsupported or malformed syntax."""


def parse_bench(text: str, *, name: str = "circuit") -> Circuit:
    """Parse the combinational subset of the common ISCAS BENCH format."""

    inputs: list[str] = []
    outputs: list[str] = []
    gates: list[Gate] = []

    for line_number, original_line in enumerate(text.splitlines(), start=1):
        line = original_line.partition("#")[0].strip()
        if not line:
            continue

        input_match = INPUT_PATTERN.fullmatch(line)
        if input_match:
            inputs.append(_identifier(input_match.group(1).strip(), line_number))
            continue

        output_match = OUTPUT_PATTERN.fullmatch(line)
        if output_match:
            outputs.append(_identifier(output_match.group(1).strip(), line_number))
            continue

        gate_match = GATE_PATTERN.fullmatch(line)
        if gate_match:
            output = _identifier(gate_match.group(1), line_number)
            kind = gate_match.group(2).upper()
            kind = GATE_ALIASES.get(kind, kind)
            if kind == "DFF":
                raise BenchError(
                    f"line {line_number}: sequential DFF circuits are not supported yet"
                )
            arguments = tuple(
                _identifier(argument.strip(), line_number, allow_constant=True)
                for argument in gate_match.group(3).split(",")
                if argument.strip()
            )
            gates.append(
                Gate(
                    name=f"g{len(gates)}",
                    kind=kind,
                    inputs=arguments,
                    output=output,
                )
            )
            continue

        raise BenchError(f"line {line_number}: cannot parse {original_line!r}")

    circuit_name = name if VERILOG_IDENTIFIER.fullmatch(name) else "circuit"
    circuit = Circuit(
        name=circuit_name,
        inputs=tuple(inputs),
        outputs=tuple(outputs),
        gates=tuple(gates),
    )
    circuit.validate()
    return circuit


def load_bench(path: Path) -> Circuit:
    try:
        text = path.read_text(encoding="utf-8")
    except (OSError, UnicodeError) as error:
        raise BenchError(f"cannot read BENCH file {path}: {error}") from error
    return parse_bench(text, name=path.stem)


def write_bench(circuit: Circuit, path: Path) -> None:
    circuit.validate()
    lines = [f"# Generated by LockLab from circuit {circuit.name}"]
    lines.extend(f"INPUT({name})" for name in circuit.inputs)
    lines.append("")
    lines.extend(f"OUTPUT({name})" for name in circuit.outputs)
    lines.append("")
    lines.extend(
        f"{gate.output} = {gate.kind}({', '.join(gate.inputs)})"
        for gate in circuit.topological_gates()
    )
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _identifier(name: str, line_number: int, *, allow_constant: bool = False) -> str:
    if allow_constant and name in {"0", "1"}:
        return name
    if VERILOG_IDENTIFIER.fullmatch(name) is None:
        raise BenchError(f"line {line_number}: unsupported signal name {name!r}")
    return name
